"""add_idempotency_key_to_transaction

Revision ID: 36579baea2da
Revises: e4b05b6eb7e4
Create Date: 2026-02-21 14:51:53.529622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36579baea2da'
down_revision: Union[str, Sequence[str], None] = 'e4b05b6eb7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(), nullable=True))
    
    # Update existing rows with a placeholder if any exist (though this is a fresh project, good practice)
    # op.execute("UPDATE transactions SET idempotency_key = id::text WHERE idempotency_key IS NULL")
    
    # Make it non-nullable if we want to enforce it (but might be better to keep nullable for existing data)
    # For now, let's keep it nullable or use a server default
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_column('transactions', 'idempotency_key')
    # ### end Alembic commands ###
